tlshd: fix a couple of compiling errors with QUIC enabled
This patch fixes these compiling errors with QUIC enabled:

client.c: In function ‘tlshd_quic_client_set_x509_session’:
client.c:489:43: error: ‘xcred’ undeclared (first use in this function);
  did you mean ‘cred’?
  489 |         ret = tlshd_client_get_truststore(xcred);
      |                                           ^~~~~
      |                                           cred

client.c:489:43: note: each undeclared identifier is reported only once
  for each function it appears in
client.c: In function ‘tlshd_quic_client_set_psk_session’:
client.c:544:31: error: incompatible types when initializing type
  ‘key_serial_t’ {aka ‘int’} using type ‘GArray’ {aka ‘struct _GArray’}
  544 |         key_serial_t peerid = conn->parms->peerids[0];
      |                               ^~~~

server.c: In function ‘tlshd_quic_server_set_x509_session’:
server.c:481:15: error: unused variable ‘cafile’ [-Werror=unused-variable]
  481 |         char *cafile;
      |               ^~~~~~

Commit fe3a78aaef92 ("tlshd: Refactor trust store management") passed
incorrect 'xcred' to tlshd_client_get_truststore(), while it should
be 'cred'. The unused variable 'cafile' should also be cleaned in
tlshd_quic_server_set_x509_session().

Commit 18b04a63fc01 ("tlshd: Store peer IDs in a GArray") forgot to
fix the parms->peerids access in tlshd_quic_client_set_psk_session().

Fixes: fe3a78aaef92 ("tlshd: Refactor trust store management")
Fixes: 18b04a63fc01 ("tlshd: Store peer IDs in a GArray")
Signed-off-by: Xin Long <lucien.xin@gmail.com>